name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform-ci:
    if: vars.TERRAFORM_CI_ENABLED != 'false'
    uses: Firecrown-Media/gh-shared-workflows/.github/workflows/terraform-ci.yml@main
    with:
      terraform_dir: .
      docs_output_file: README.md
      skip_terraform_validate: false
      trivy_config: trivy.yaml
      trivyignore_path: .trivyignore
